# Generated by Django 3.1.6 on 2021-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0002_auto_20210212_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_link',
            field=models.CharField(default='https://codepen.io', max_length=1000),
        ),
    ]
